package com.ems.lite.admin.utils

object IntentConstants {
    const val ID = "id"
    const val VALUE = "value"
    const val TYPE = "type"
    const val VILLAGE_NO = "village_no"
    const val BOOTH_NO = "booth_no"
    const val BOOTH_NAME = "booth_name"
    const val MAX = "MAX"
    const val MIN = "MIN"
    const val USER = "user"
    const val ASSEMBLY = "assembly"
    const val DIVISION = "division"
    const val VILLAGE = "village"
    const val BOOTH = "booth"
    const val VOTER = "voter"
    const val VOTER_ID = "voter_id"
    const val SHOW_ALL_OPTION = "show_all_option"
    const val CARD_NO = "card_no"
    const val FROM = "from"
    const val SURNAME = "surname"
    const val ORGANIZATION = "organization"
    const val OFFICIALS = "officials"
    const val ISSUE = "issue"
    const val ISSUE_FOLLOW_UP = "issue_follow_up"
    const val DEV_WORK = "dev_work"
    const val HOUSE_NO = "house_no"
    const val RELATIVE = "relative"
}